# Generated by Django 4.2.6 on 2023-11-01 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWSP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "celular",
                    models.CharField(
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El número debe ser en formato: +999999999. Hasta 15 digitos permitidos.",
                                regex="\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ciudad",
                    models.CharField(
                        blank=True,
                        choices=[("Villa Maria", "Villa Maria"), ("Villa Nueva", "Villa Nueva")],
                        max_length=25,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario de WhatsApp",
                "verbose_name_plural": "Usuarios de WhatsApp",
            },
        ),
    ]
